baseURL = 'https://m4dd.rocks/'
languageCode = 'en-us'
title = 'm4dd.rocks'

[markup.tableOfContents]
    endLevel = 6
    startLevel = 1

[pagination]
    disableAliases = false
    pagerSize = 5
    path = 'page'
